import type { Metadata } from "next";
import "./default.css";
import "typeface-roboto";
import { Grommet } from "grommet";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = {
  global: {
    font: {
      family: "Roboto",
      size: "18px",
      height: "20px",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Grommet full theme={theme}>
            {children}
          </Grommet>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
