/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeMistakesIndexRouteImport } from './routes/home/mistakes/index'
import { Route as HomeBlessingsIndexRouteImport } from './routes/home/blessings/index'
import { Route as HomeAccountsIndexRouteImport } from './routes/home/accounts/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeMistakesIndexRoute = HomeMistakesIndexRouteImport.update({
  id: '/home/mistakes/',
  path: '/home/mistakes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBlessingsIndexRoute = HomeBlessingsIndexRouteImport.update({
  id: '/home/blessings/',
  path: '/home/blessings/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAccountsIndexRoute = HomeAccountsIndexRouteImport.update({
  id: '/home/accounts/',
  path: '/home/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/': typeof HomeIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/home/accounts/': typeof HomeAccountsIndexRoute
  '/home/blessings/': typeof HomeBlessingsIndexRoute
  '/home/mistakes/': typeof HomeMistakesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/home/accounts': typeof HomeAccountsIndexRoute
  '/home/blessings': typeof HomeBlessingsIndexRoute
  '/home/mistakes': typeof HomeMistakesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home/': typeof HomeIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/home/accounts/': typeof HomeAccountsIndexRoute
  '/home/blessings/': typeof HomeBlessingsIndexRoute
  '/home/mistakes/': typeof HomeMistakesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/'
    | '/sign-up/'
    | '/home/accounts/'
    | '/home/blessings/'
    | '/home/mistakes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/sign-up'
    | '/home/accounts'
    | '/home/blessings'
    | '/home/mistakes'
  id:
    | '__root__'
    | '/'
    | '/home/'
    | '/sign-up/'
    | '/home/accounts/'
    | '/home/blessings/'
    | '/home/mistakes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  HomeAccountsIndexRoute: typeof HomeAccountsIndexRoute
  HomeBlessingsIndexRoute: typeof HomeBlessingsIndexRoute
  HomeMistakesIndexRoute: typeof HomeMistakesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/mistakes/': {
      id: '/home/mistakes/'
      path: '/home/mistakes'
      fullPath: '/home/mistakes/'
      preLoaderRoute: typeof HomeMistakesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/blessings/': {
      id: '/home/blessings/'
      path: '/home/blessings'
      fullPath: '/home/blessings/'
      preLoaderRoute: typeof HomeBlessingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/accounts/': {
      id: '/home/accounts/'
      path: '/home/accounts'
      fullPath: '/home/accounts/'
      preLoaderRoute: typeof HomeAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  HomeAccountsIndexRoute: HomeAccountsIndexRoute,
  HomeBlessingsIndexRoute: HomeBlessingsIndexRoute,
  HomeMistakesIndexRoute: HomeMistakesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
