/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as FinancialDramaIndexRouteImport } from './routes/financial-drama/index'
import { Route as FinancialDramaIdRouteImport } from './routes/financial-drama/$id'
import { Route as HomeRecurringIndexRouteImport } from './routes/home/recurring/index'
import { Route as HomeMistakesIndexRouteImport } from './routes/home/mistakes/index'
import { Route as HomeBlessingsIndexRouteImport } from './routes/home/blessings/index'
import { Route as HomeAccountsIndexRouteImport } from './routes/home/accounts/index'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const FinancialDramaIndexRoute = FinancialDramaIndexRouteImport.update({
  id: '/financial-drama/',
  path: '/financial-drama/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialDramaIdRoute = FinancialDramaIdRouteImport.update({
  id: '/financial-drama/$id',
  path: '/financial-drama/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRecurringIndexRoute = HomeRecurringIndexRouteImport.update({
  id: '/recurring/',
  path: '/recurring/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMistakesIndexRoute = HomeMistakesIndexRouteImport.update({
  id: '/mistakes/',
  path: '/mistakes/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeBlessingsIndexRoute = HomeBlessingsIndexRouteImport.update({
  id: '/blessings/',
  path: '/blessings/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAccountsIndexRoute = HomeAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/financial-drama/$id': typeof FinancialDramaIdRoute
  '/financial-drama/': typeof FinancialDramaIndexRoute
  '/home/': typeof HomeIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/home/accounts/': typeof HomeAccountsIndexRoute
  '/home/blessings/': typeof HomeBlessingsIndexRoute
  '/home/mistakes/': typeof HomeMistakesIndexRoute
  '/home/recurring/': typeof HomeRecurringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financial-drama/$id': typeof FinancialDramaIdRoute
  '/financial-drama': typeof FinancialDramaIndexRoute
  '/home': typeof HomeIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/home/accounts': typeof HomeAccountsIndexRoute
  '/home/blessings': typeof HomeBlessingsIndexRoute
  '/home/mistakes': typeof HomeMistakesIndexRoute
  '/home/recurring': typeof HomeRecurringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/financial-drama/$id': typeof FinancialDramaIdRoute
  '/financial-drama/': typeof FinancialDramaIndexRoute
  '/home/': typeof HomeIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/home/accounts/': typeof HomeAccountsIndexRoute
  '/home/blessings/': typeof HomeBlessingsIndexRoute
  '/home/mistakes/': typeof HomeMistakesIndexRoute
  '/home/recurring/': typeof HomeRecurringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/financial-drama/$id'
    | '/financial-drama/'
    | '/home/'
    | '/sign-up/'
    | '/home/accounts/'
    | '/home/blessings/'
    | '/home/mistakes/'
    | '/home/recurring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financial-drama/$id'
    | '/financial-drama'
    | '/home'
    | '/sign-up'
    | '/home/accounts'
    | '/home/blessings'
    | '/home/mistakes'
    | '/home/recurring'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/financial-drama/$id'
    | '/financial-drama/'
    | '/home/'
    | '/sign-up/'
    | '/home/accounts/'
    | '/home/blessings/'
    | '/home/mistakes/'
    | '/home/recurring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  FinancialDramaIdRoute: typeof FinancialDramaIdRoute
  FinancialDramaIndexRoute: typeof FinancialDramaIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/financial-drama/': {
      id: '/financial-drama/'
      path: '/financial-drama'
      fullPath: '/financial-drama/'
      preLoaderRoute: typeof FinancialDramaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-drama/$id': {
      id: '/financial-drama/$id'
      path: '/financial-drama/$id'
      fullPath: '/financial-drama/$id'
      preLoaderRoute: typeof FinancialDramaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/recurring/': {
      id: '/home/recurring/'
      path: '/recurring'
      fullPath: '/home/recurring/'
      preLoaderRoute: typeof HomeRecurringIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/mistakes/': {
      id: '/home/mistakes/'
      path: '/mistakes'
      fullPath: '/home/mistakes/'
      preLoaderRoute: typeof HomeMistakesIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/blessings/': {
      id: '/home/blessings/'
      path: '/blessings'
      fullPath: '/home/blessings/'
      preLoaderRoute: typeof HomeBlessingsIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/accounts/': {
      id: '/home/accounts/'
      path: '/accounts'
      fullPath: '/home/accounts/'
      preLoaderRoute: typeof HomeAccountsIndexRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAccountsIndexRoute: typeof HomeAccountsIndexRoute
  HomeBlessingsIndexRoute: typeof HomeBlessingsIndexRoute
  HomeMistakesIndexRoute: typeof HomeMistakesIndexRoute
  HomeRecurringIndexRoute: typeof HomeRecurringIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeAccountsIndexRoute: HomeAccountsIndexRoute,
  HomeBlessingsIndexRoute: HomeBlessingsIndexRoute,
  HomeMistakesIndexRoute: HomeMistakesIndexRoute,
  HomeRecurringIndexRoute: HomeRecurringIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  FinancialDramaIdRoute: FinancialDramaIdRoute,
  FinancialDramaIndexRoute: FinancialDramaIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
